repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.1 # Do not change version. 0.6.0 introduces breaking changes.
    hooks:
    - id: mdformat
      exclude: "CHANGELOG.md|docs/mkdocs_code_of_conduct.md|docs/api_reference"
      additional_dependencies:
      - mdformat-tables
      - mdformat-config
      - mdformat-frontmatter
      - mdformat-gfm
